{% set name = "metar" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3f63910815f8050e1c4e276e87aacfd1b86fde4304eac91029dd20884f5d189b

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - metar

about:
  home: http://github.com/python-metar/python-metar
  license: MIT
  license_family: MIT

  ## Currently the license isn't available in the pypi build. we'll
  ## uncomment this line later after the next release.
  #license_file: LICENSE
  summary: |
    python-metar is a python package that parses coded METAR weather reports.
  description: |
    python-metar is a python package that parses coded METAR weather reports.
  doc_url: https://github.com/python-metar/python-metar
  dev_url: https://github.com/python-metar/python-metar

extra:
  recipe-maintainers:
    - phobson
    - akrherz
