{% set version = "1.11.0" %}

package:
  name: metar
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/m/metar/metar-{{ version }}.tar.gz
  sha256: 0e40e86eb03fdfafef71b14d74349e88e208bd4dc15e8734b3afcf129125378b

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - metar

about:
  home: http://github.com/python-metar/python-metar
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: |
    python-metar is a python package that parses coded METAR weather reports.
  description: |
    python-metar is a python package that parses coded METAR weather reports.
  doc_url: https://github.com/python-metar/python-metar
  dev_url: https://github.com/python-metar/python-metar

extra:
  recipe-maintainers:
    - phobson
    - akrherz
